project:
  type: website

execute:
  freeze: auto
  
website:
  title: Nicolas P. Rougier
  site-url: https://www.labri.fr/perso/nrougier
  description: "Nicolas P. Rougier posts"  
  favicon: data/gravatar-black.png
  page-navigation: true
  navbar:
    title: false 
    logo: data/gravatar-white.png
    left:
      - href: index.qmd
        text: HOME
      - href: resume.qmd
        text: RESUME
      - href: activities.qmd
        text: ACTIVITIES
      - href: contributions.qmd
        text: CONTRIBUTIONS
      - href: artwork.qmd
        text: ARTWORK
      - href: news.qmd
        text: NEWS
      - href: blog.qmd
        text: BLOG
      - href: https://github.com/rougier
        text: CODE
    tools:
      - icon: envelope
        href: mailto:nicolas.rougier@inria.fr
      - icon: mastodon
        href: https://toot.aquilenet.fr/@rougier
      - icon: reddit
        href: https://www.reddit.com/user/Nicolas-Rougier
      - icon: github
        href: https://github.com/rougier
      - icon: rss
        href: blog.xml
        
  page-footer:
     background: primary
     center: |
       Made with Quarto (sketchy theme).<br>
       Last updated: {{< meta date-modified >}}

format:
  html:
    date-modified: last-modified
    title-block-style: none
    theme:
      - sketchy
    css: styles.css
    toc: true




